name: UltimateCatcher
description: UltimateCatcher
version: maven-version-number
main: com.songoda.ultimatecatcher.UltimateCatcher
softdepend: [UltimateStacker, WorldGuard]
author: songoda
api-version: 1.13
commands:
  uc:
    description: I have no idea.
    default: true
    aliases: [UltimateCatcher]
    usage: /<command> [reload]